mkdir disasm
mkdir disasm\battles
mkdir disasm\battles\global
mkdir disasm\battles\entries
FOR /L %%G IN (0,1,9) DO mkdir disasm\battles\entries\battle0%%G
FOR /L %%G IN (10,1,44) DO mkdir disasm\battles\entries\battle%%G
mkdir disasm\maps
mkdir disasm\maps\global
mkdir disasm\maps\entries
FOR /L %%G IN (0,1,9) DO mkdir disasm\maps\entries\map0%%G
FOR /L %%G IN (10,1,78) DO mkdir disasm\maps\entries\map%%G
FOR /L %%G IN (0,1,9) DO mkdir disasm\maps\entries\map0%%G\mapsetups
FOR /L %%G IN (10,1,78) DO mkdir disasm\maps\entries\map%%G\mapsetups
mkdir disasm\scripting
mkdir disasm\scripting\textbanks
mkdir disasm\scripting\entityactscripts
mkdir disasm\scripting\mapscripts
mkdir disasm\scripting\cutscenes
mkdir disasm\romlayout
mkdir disasm\system
mkdir disasm\system\interrupts
mkdir disasm\system\tech
mkdir disasm\system\vints
mkdir disasm\system\init
mkdir disasm\system\sound
mkdir disasm\system\windows
mkdir disasm\system\sram
mkdir disasm\system\debug
mkdir disasm\system\debug\debug
mkdir disasm\system\debug\conf
mkdir disasm\system\exploration
mkdir disasm\system\exploration\vints
mkdir disasm\system\menus\
mkdir disasm\system\menus\main
mkdir disasm\system\menus\shop
mkdir disasm\system\menus\church
mkdir disasm\system\menus\caravan
mkdir disasm\system\menus\blacksmith
mkdir disasm\system\stats
mkdir disasm\system\stats\allies
mkdir disasm\system\stats\enemies
mkdir disasm\system\maps
mkdir disasm\system\text
mkdir disasm\system\battles
mkdir disasm\system\battles\vints
mkdir disasm\system\battles\battlescenes
mkdir disasm\system\battles\battlescenes\spells
mkdir disasm\system\battles\specialsprites
mkdir disasm\system\battles\ai
mkdir disasm\system\items
mkdir disasm\system\scripting
mkdir disasm\system\scripting\entity
mkdir disasm\system\scripting\map
mkdir disasm\system\specialscreens
mkdir disasm\system\specialscreens\segalogo
mkdir disasm\system\specialscreens\title
mkdir disasm\system\specialscreens\witch
mkdir disasm\system\specialscreens\suspend
mkdir disasm\system\specialscreens\endkiss
mkdir disasm\system\specialscreens\credits
mkdir disasm\system\specialscreens\witchend
mkdir disasm\system\specialscreens\jewelend
mkdir disasm\system\graphics
mkdir disasm\system\unidentified
mkdir disasm\data
mkdir disasm\data\allies
mkdir disasm\data\allies\stats
mkdir disasm\graphics
mkdir disasm\graphics\mapsprites
mkdir disasm\graphics\portraits
mkdir disasm\graphics\battles
mkdir disasm\graphics\battles\grounds
mkdir disasm\graphics\battles\backgrounds
mkdir disasm\graphics\battles\weapons
mkdir disasm\graphics\battles\battlesprites
mkdir disasm\graphics\battles\battlesprites\allies
mkdir disasm\graphics\battles\battlesprites\allies\animations
mkdir disasm\graphics\battles\battlesprites\enemies
mkdir disasm\graphics\battles\battlesprites\enemies\animations
mkdir disasm\graphics\battles\spells
mkdir disasm\graphics\battles\spells\invocations
mkdir disasm\graphics\battles\spells\animations
pause